---
title: "TypeError: vocab() got an unexpected keyword argument 'specials'"
date:   2023-02-01
excerpt: "RNN 구현 오류"
category: [Error]
layout: post
tag:
- Error
order: 0

comments: true
---

# torchtext.vocab error
데이터 전처리를 하고있었는데 계속 이런에러가 떴다 (5시간동안 버전 다 바꿔보고 삽질했다..) 


```python
from torchtext.vocab import vocab

...

src_vocab = vocab(src_, specials=special_symbols, special_first=True) 
```

```python
TypeError: vocab() got an unexpected keyword argument 'specials'
```



---

# Solve
[torchtext.vocab](https://pytorch.org/text/stable/vocab.html)를 찾아보니 아래도 같은 기능을해서 아래와 같이 바꿔주면된다.      

아니면 vsc에서만 안되는 것 일 수 있으므로 코랩 프로에서 돌려보자.    

(난 코랩에선 돌아갔다.)

아래와 같이 고쳐주면 vsc에서도 돌아간다.  

근데 0.10.0에서 부터 지원하는거 보면 버전문제인 것 같긴한데 나는 버전을 다 바꿔봐도 안됐다,,,,,ㅠㅠㅠ

```python
from torchtext.vocab import build_vocab_from_iterator

...

src_vocab = build_vocab_from_iterator(src_, specials=special_symbols, special_first=True) #vocab
```
